version: '3.8'
services:
  postgres:
    image: postgres:15-alpine
    container_name: my-java-db
    environment:
      POSTGRES_USER: dev_user
      POSTGRES_PASSWORD: dev_password
      POSTGRES_DB: first_api_db
    ports:
      - "5432:5432"